/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users.index'
import { Route as AdminPlansIndexRouteImport } from './routes/_admin/plans.index'
import { Route as AdminAmbassadorsIndexRouteImport } from './routes/_admin/ambassadors.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users.$userId'
import { Route as AdminPlansNewRouteImport } from './routes/_admin/plans.new'
import { Route as AdminPlansPlanIdRouteImport } from './routes/_admin/plans.$planId'
import { Route as AdminAmbassadorsIdRouteImport } from './routes/_admin/ambassadors.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbassadorsIndexRoute = AdminAmbassadorsIndexRouteImport.update({
  id: '/ambassadors/',
  path: '/ambassadors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansNewRoute = AdminPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansPlanIdRoute = AdminPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbassadorsIdRoute = AdminAmbassadorsIdRouteImport.update({
  id: '/ambassadors/$id',
  path: '/ambassadors/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/ambassadors/$id': typeof AdminAmbassadorsIdRoute
  '/plans/$planId': typeof AdminPlansPlanIdRoute
  '/plans/new': typeof AdminPlansNewRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/ambassadors/': typeof AdminAmbassadorsIndexRoute
  '/plans/': typeof AdminPlansIndexRoute
  '/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/ambassadors/$id': typeof AdminAmbassadorsIdRoute
  '/plans/$planId': typeof AdminPlansPlanIdRoute
  '/plans/new': typeof AdminPlansNewRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/ambassadors': typeof AdminAmbassadorsIndexRoute
  '/plans': typeof AdminPlansIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/ambassadors/$id': typeof AdminAmbassadorsIdRoute
  '/_admin/plans/$planId': typeof AdminPlansPlanIdRoute
  '/_admin/plans/new': typeof AdminPlansNewRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_admin/ambassadors/': typeof AdminAmbassadorsIndexRoute
  '/_admin/plans/': typeof AdminPlansIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/notifications'
    | '/ambassadors/$id'
    | '/plans/$planId'
    | '/plans/new'
    | '/users/$userId'
    | '/ambassadors/'
    | '/plans/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/notifications'
    | '/ambassadors/$id'
    | '/plans/$planId'
    | '/plans/new'
    | '/users/$userId'
    | '/ambassadors'
    | '/plans'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/notifications'
    | '/_admin/ambassadors/$id'
    | '/_admin/plans/$planId'
    | '/_admin/plans/new'
    | '/_admin/users/$userId'
    | '/_admin/ambassadors/'
    | '/_admin/plans/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans/': {
      id: '/_admin/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ambassadors/': {
      id: '/_admin/ambassadors/'
      path: '/ambassadors'
      fullPath: '/ambassadors/'
      preLoaderRoute: typeof AdminAmbassadorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans/new': {
      id: '/_admin/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof AdminPlansNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans/$planId': {
      id: '/_admin/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AdminPlansPlanIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ambassadors/$id': {
      id: '/_admin/ambassadors/$id'
      path: '/ambassadors/$id'
      fullPath: '/ambassadors/$id'
      preLoaderRoute: typeof AdminAmbassadorsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminAmbassadorsIdRoute: typeof AdminAmbassadorsIdRoute
  AdminPlansPlanIdRoute: typeof AdminPlansPlanIdRoute
  AdminPlansNewRoute: typeof AdminPlansNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAmbassadorsIndexRoute: typeof AdminAmbassadorsIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminAmbassadorsIdRoute: AdminAmbassadorsIdRoute,
  AdminPlansPlanIdRoute: AdminPlansPlanIdRoute,
  AdminPlansNewRoute: AdminPlansNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAmbassadorsIndexRoute: AdminAmbassadorsIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
