/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPomodoroRouteImport } from './routes/_app/pomodoro'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBrainRouteImport } from './routes/_app/brain'
import { Route as AppApiDocsRouteImport } from './routes/_app/api-docs'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppRitualsIndexRouteImport } from './routes/_app/rituals/index'
import { Route as AppHabitsIndexRouteImport } from './routes/_app/habits/index'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppTasksWeeklyRouteImport } from './routes/_app/tasks/weekly'
import { Route as AppTasksTodayRouteImport } from './routes/_app/tasks/today'
import { Route as AppTasksStatsRouteImport } from './routes/_app/tasks/stats'
import { Route as AppTasksBacklogRouteImport } from './routes/_app/tasks/backlog'
import { Route as AppTasksAllRouteImport } from './routes/_app/tasks/all'
import { Route as AppRitualsKindRouteImport } from './routes/_app/rituals/$kind'
import { Route as AppHabitsTrackerRouteImport } from './routes/_app/habits/tracker'
import { Route as AppHabitsStatsRouteImport } from './routes/_app/habits/stats'
import { Route as AppHabitsListRouteImport } from './routes/_app/habits/list'
import { Route as AppGoalsWeeklyRouteImport } from './routes/_app/goals/weekly'
import { Route as AppGoalsTreeRouteImport } from './routes/_app/goals/tree'
import { Route as AppGoalsMineRouteImport } from './routes/_app/goals/mine'
import { Route as AppGoalsMetricsRouteImport } from './routes/_app/goals/metrics'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppApiDocsRoute = AppApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppRitualsIndexRoute = AppRitualsIndexRouteImport.update({
  id: '/rituals/',
  path: '/rituals/',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsIndexRoute = AppHabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksWeeklyRoute = AppTasksWeeklyRouteImport.update({
  id: '/tasks/weekly',
  path: '/tasks/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTodayRoute = AppTasksTodayRouteImport.update({
  id: '/tasks/today',
  path: '/tasks/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksStatsRoute = AppTasksStatsRouteImport.update({
  id: '/tasks/stats',
  path: '/tasks/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksBacklogRoute = AppTasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksAllRoute = AppTasksAllRouteImport.update({
  id: '/tasks/all',
  path: '/tasks/all',
  getParentRoute: () => AppRoute,
} as any)
const AppRitualsKindRoute = AppRitualsKindRouteImport.update({
  id: '/rituals/$kind',
  path: '/rituals/$kind',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsTrackerRoute = AppHabitsTrackerRouteImport.update({
  id: '/habits/tracker',
  path: '/habits/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsStatsRoute = AppHabitsStatsRouteImport.update({
  id: '/habits/stats',
  path: '/habits/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsListRoute = AppHabitsListRouteImport.update({
  id: '/habits/list',
  path: '/habits/list',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsWeeklyRoute = AppGoalsWeeklyRouteImport.update({
  id: '/goals/weekly',
  path: '/goals/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsTreeRoute = AppGoalsTreeRouteImport.update({
  id: '/goals/tree',
  path: '/goals/tree',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsMineRoute = AppGoalsMineRouteImport.update({
  id: '/goals/mine',
  path: '/goals/mine',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsMetricsRoute = AppGoalsMetricsRouteImport.update({
  id: '/goals/metrics',
  path: '/goals/metrics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof AppSplatRoute
  '/ai': typeof AppAiRoute
  '/api-docs': typeof AppApiDocsRoute
  '/brain': typeof AppBrainRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/goals/metrics': typeof AppGoalsMetricsRoute
  '/goals/mine': typeof AppGoalsMineRoute
  '/goals/tree': typeof AppGoalsTreeRoute
  '/goals/weekly': typeof AppGoalsWeeklyRoute
  '/habits/list': typeof AppHabitsListRoute
  '/habits/stats': typeof AppHabitsStatsRoute
  '/habits/tracker': typeof AppHabitsTrackerRoute
  '/rituals/$kind': typeof AppRitualsKindRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/backlog': typeof AppTasksBacklogRoute
  '/tasks/stats': typeof AppTasksStatsRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/tasks/weekly': typeof AppTasksWeeklyRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/habits/': typeof AppHabitsIndexRoute
  '/rituals/': typeof AppRitualsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof AppSplatRoute
  '/ai': typeof AppAiRoute
  '/api-docs': typeof AppApiDocsRoute
  '/brain': typeof AppBrainRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/goals/metrics': typeof AppGoalsMetricsRoute
  '/goals/mine': typeof AppGoalsMineRoute
  '/goals/tree': typeof AppGoalsTreeRoute
  '/goals/weekly': typeof AppGoalsWeeklyRoute
  '/habits/list': typeof AppHabitsListRoute
  '/habits/stats': typeof AppHabitsStatsRoute
  '/habits/tracker': typeof AppHabitsTrackerRoute
  '/rituals/$kind': typeof AppRitualsKindRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/backlog': typeof AppTasksBacklogRoute
  '/tasks/stats': typeof AppTasksStatsRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/tasks/weekly': typeof AppTasksWeeklyRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/goals': typeof AppGoalsIndexRoute
  '/habits': typeof AppHabitsIndexRoute
  '/rituals': typeof AppRitualsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/api-docs': typeof AppApiDocsRoute
  '/_app/brain': typeof AppBrainRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pomodoro': typeof AppPomodoroRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/goals/metrics': typeof AppGoalsMetricsRoute
  '/_app/goals/mine': typeof AppGoalsMineRoute
  '/_app/goals/tree': typeof AppGoalsTreeRoute
  '/_app/goals/weekly': typeof AppGoalsWeeklyRoute
  '/_app/habits/list': typeof AppHabitsListRoute
  '/_app/habits/stats': typeof AppHabitsStatsRoute
  '/_app/habits/tracker': typeof AppHabitsTrackerRoute
  '/_app/rituals/$kind': typeof AppRitualsKindRoute
  '/_app/tasks/all': typeof AppTasksAllRoute
  '/_app/tasks/backlog': typeof AppTasksBacklogRoute
  '/_app/tasks/stats': typeof AppTasksStatsRoute
  '/_app/tasks/today': typeof AppTasksTodayRoute
  '/_app/tasks/weekly': typeof AppTasksWeeklyRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/habits/': typeof AppHabitsIndexRoute
  '/_app/rituals/': typeof AppRitualsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai'
    | '/api-docs'
    | '/brain'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/pomodoro'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/goals/metrics'
    | '/goals/mine'
    | '/goals/tree'
    | '/goals/weekly'
    | '/habits/list'
    | '/habits/stats'
    | '/habits/tracker'
    | '/rituals/$kind'
    | '/tasks/all'
    | '/tasks/backlog'
    | '/tasks/stats'
    | '/tasks/today'
    | '/tasks/weekly'
    | '/calendar/'
    | '/goals/'
    | '/habits/'
    | '/rituals/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai'
    | '/api-docs'
    | '/brain'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/pomodoro'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/goals/metrics'
    | '/goals/mine'
    | '/goals/tree'
    | '/goals/weekly'
    | '/habits/list'
    | '/habits/stats'
    | '/habits/tracker'
    | '/rituals/$kind'
    | '/tasks/all'
    | '/tasks/backlog'
    | '/tasks/stats'
    | '/tasks/today'
    | '/tasks/weekly'
    | '/calendar'
    | '/goals'
    | '/habits'
    | '/rituals'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/$'
    | '/_app/ai'
    | '/_app/api-docs'
    | '/_app/brain'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/pomodoro'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/goals/metrics'
    | '/_app/goals/mine'
    | '/_app/goals/tree'
    | '/_app/goals/weekly'
    | '/_app/habits/list'
    | '/_app/habits/stats'
    | '/_app/habits/tracker'
    | '/_app/rituals/$kind'
    | '/_app/tasks/all'
    | '/_app/tasks/backlog'
    | '/_app/tasks/stats'
    | '/_app/tasks/today'
    | '/_app/tasks/weekly'
    | '/_app/calendar/'
    | '/_app/goals/'
    | '/_app/habits/'
    | '/_app/rituals/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pomodoro': {
      id: '/_app/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain': {
      id: '/_app/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-docs': {
      id: '/_app/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AppApiDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rituals/': {
      id: '/_app/rituals/'
      path: '/rituals'
      fullPath: '/rituals/'
      preLoaderRoute: typeof AppRitualsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/': {
      id: '/_app/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof AppHabitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/weekly': {
      id: '/_app/tasks/weekly'
      path: '/tasks/weekly'
      fullPath: '/tasks/weekly'
      preLoaderRoute: typeof AppTasksWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/today': {
      id: '/_app/tasks/today'
      path: '/tasks/today'
      fullPath: '/tasks/today'
      preLoaderRoute: typeof AppTasksTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/stats': {
      id: '/_app/tasks/stats'
      path: '/tasks/stats'
      fullPath: '/tasks/stats'
      preLoaderRoute: typeof AppTasksStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/backlog': {
      id: '/_app/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof AppTasksBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/all': {
      id: '/_app/tasks/all'
      path: '/tasks/all'
      fullPath: '/tasks/all'
      preLoaderRoute: typeof AppTasksAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rituals/$kind': {
      id: '/_app/rituals/$kind'
      path: '/rituals/$kind'
      fullPath: '/rituals/$kind'
      preLoaderRoute: typeof AppRitualsKindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/tracker': {
      id: '/_app/habits/tracker'
      path: '/habits/tracker'
      fullPath: '/habits/tracker'
      preLoaderRoute: typeof AppHabitsTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/stats': {
      id: '/_app/habits/stats'
      path: '/habits/stats'
      fullPath: '/habits/stats'
      preLoaderRoute: typeof AppHabitsStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/list': {
      id: '/_app/habits/list'
      path: '/habits/list'
      fullPath: '/habits/list'
      preLoaderRoute: typeof AppHabitsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/weekly': {
      id: '/_app/goals/weekly'
      path: '/goals/weekly'
      fullPath: '/goals/weekly'
      preLoaderRoute: typeof AppGoalsWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/tree': {
      id: '/_app/goals/tree'
      path: '/goals/tree'
      fullPath: '/goals/tree'
      preLoaderRoute: typeof AppGoalsTreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/mine': {
      id: '/_app/goals/mine'
      path: '/goals/mine'
      fullPath: '/goals/mine'
      preLoaderRoute: typeof AppGoalsMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/metrics': {
      id: '/_app/goals/metrics'
      path: '/goals/metrics'
      fullPath: '/goals/metrics'
      preLoaderRoute: typeof AppGoalsMetricsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAiRoute: typeof AppAiRoute
  AppApiDocsRoute: typeof AppApiDocsRoute
  AppBrainRoute: typeof AppBrainRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppGoalsMetricsRoute: typeof AppGoalsMetricsRoute
  AppGoalsMineRoute: typeof AppGoalsMineRoute
  AppGoalsTreeRoute: typeof AppGoalsTreeRoute
  AppGoalsWeeklyRoute: typeof AppGoalsWeeklyRoute
  AppHabitsListRoute: typeof AppHabitsListRoute
  AppHabitsStatsRoute: typeof AppHabitsStatsRoute
  AppHabitsTrackerRoute: typeof AppHabitsTrackerRoute
  AppRitualsKindRoute: typeof AppRitualsKindRoute
  AppTasksAllRoute: typeof AppTasksAllRoute
  AppTasksBacklogRoute: typeof AppTasksBacklogRoute
  AppTasksStatsRoute: typeof AppTasksStatsRoute
  AppTasksTodayRoute: typeof AppTasksTodayRoute
  AppTasksWeeklyRoute: typeof AppTasksWeeklyRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppHabitsIndexRoute: typeof AppHabitsIndexRoute
  AppRitualsIndexRoute: typeof AppRitualsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAiRoute: AppAiRoute,
  AppApiDocsRoute: AppApiDocsRoute,
  AppBrainRoute: AppBrainRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppGoalsMetricsRoute: AppGoalsMetricsRoute,
  AppGoalsMineRoute: AppGoalsMineRoute,
  AppGoalsTreeRoute: AppGoalsTreeRoute,
  AppGoalsWeeklyRoute: AppGoalsWeeklyRoute,
  AppHabitsListRoute: AppHabitsListRoute,
  AppHabitsStatsRoute: AppHabitsStatsRoute,
  AppHabitsTrackerRoute: AppHabitsTrackerRoute,
  AppRitualsKindRoute: AppRitualsKindRoute,
  AppTasksAllRoute: AppTasksAllRoute,
  AppTasksBacklogRoute: AppTasksBacklogRoute,
  AppTasksStatsRoute: AppTasksStatsRoute,
  AppTasksTodayRoute: AppTasksTodayRoute,
  AppTasksWeeklyRoute: AppTasksWeeklyRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppHabitsIndexRoute: AppHabitsIndexRoute,
  AppRitualsIndexRoute: AppRitualsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
