/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPomodoroRouteImport } from './routes/_app/pomodoro'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppHabitsRouteImport } from './routes/_app/habits'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppReadingIndexRouteImport } from './routes/_app/reading/index'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes/index'
import { Route as AppFinancesIndexRouteImport } from './routes/_app/finances/index'
import { Route as AppTasksWeeklyRouteImport } from './routes/_app/tasks/weekly'
import { Route as AppTasksTodayRouteImport } from './routes/_app/tasks/today'
import { Route as AppTasksStatsRouteImport } from './routes/_app/tasks/stats'
import { Route as AppTasksBacklogRouteImport } from './routes/_app/tasks/backlog'
import { Route as AppTasksAllRouteImport } from './routes/_app/tasks/all'
import { Route as AppReadingLibraryRouteImport } from './routes/_app/reading/library'
import { Route as AppNotesTrashRouteImport } from './routes/_app/notes/trash'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as AppFinancesSavingsRouteImport } from './routes/_app/finances/savings'
import { Route as AppFinancesRecurringRouteImport } from './routes/_app/finances/recurring'
import { Route as AppFinancesMonthlyRouteImport } from './routes/_app/finances/monthly'
import { Route as AppFinancesInvestmentsRouteImport } from './routes/_app/finances/investments'
import { Route as AppFinancesIncomeRouteImport } from './routes/_app/finances/income'
import { Route as AppFinancesHistoryRouteImport } from './routes/_app/finances/history'
import { Route as AppFinancesDebtsRouteImport } from './routes/_app/finances/debts'
import { Route as AppFinancesAccountsRouteImport } from './routes/_app/finances/accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingIndexRoute = AppReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesIndexRoute = AppFinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksWeeklyRoute = AppTasksWeeklyRouteImport.update({
  id: '/tasks/weekly',
  path: '/tasks/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTodayRoute = AppTasksTodayRouteImport.update({
  id: '/tasks/today',
  path: '/tasks/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksStatsRoute = AppTasksStatsRouteImport.update({
  id: '/tasks/stats',
  path: '/tasks/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksBacklogRoute = AppTasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksAllRoute = AppTasksAllRouteImport.update({
  id: '/tasks/all',
  path: '/tasks/all',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingLibraryRoute = AppReadingLibraryRouteImport.update({
  id: '/reading/library',
  path: '/reading/library',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesTrashRoute = AppNotesTrashRouteImport.update({
  id: '/notes/trash',
  path: '/notes/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesSavingsRoute = AppFinancesSavingsRouteImport.update({
  id: '/finances/savings',
  path: '/finances/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRecurringRoute = AppFinancesRecurringRouteImport.update({
  id: '/finances/recurring',
  path: '/finances/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesMonthlyRoute = AppFinancesMonthlyRouteImport.update({
  id: '/finances/monthly',
  path: '/finances/monthly',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesInvestmentsRoute = AppFinancesInvestmentsRouteImport.update({
  id: '/finances/investments',
  path: '/finances/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesIncomeRoute = AppFinancesIncomeRouteImport.update({
  id: '/finances/income',
  path: '/finances/income',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesHistoryRoute = AppFinancesHistoryRouteImport.update({
  id: '/finances/history',
  path: '/finances/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesDebtsRoute = AppFinancesDebtsRouteImport.update({
  id: '/finances/debts',
  path: '/finances/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesAccountsRoute = AppFinancesAccountsRouteImport.update({
  id: '/finances/accounts',
  path: '/finances/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof AppSplatRoute
  '/ai': typeof AppAiRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/habits': typeof AppHabitsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/finances/accounts': typeof AppFinancesAccountsRoute
  '/finances/debts': typeof AppFinancesDebtsRoute
  '/finances/history': typeof AppFinancesHistoryRoute
  '/finances/income': typeof AppFinancesIncomeRoute
  '/finances/investments': typeof AppFinancesInvestmentsRoute
  '/finances/monthly': typeof AppFinancesMonthlyRoute
  '/finances/recurring': typeof AppFinancesRecurringRoute
  '/finances/savings': typeof AppFinancesSavingsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/trash': typeof AppNotesTrashRoute
  '/reading/library': typeof AppReadingLibraryRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/backlog': typeof AppTasksBacklogRoute
  '/tasks/stats': typeof AppTasksStatsRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/tasks/weekly': typeof AppTasksWeeklyRoute
  '/finances/': typeof AppFinancesIndexRoute
  '/notes/': typeof AppNotesIndexRoute
  '/reading/': typeof AppReadingIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof AppSplatRoute
  '/ai': typeof AppAiRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/habits': typeof AppHabitsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/finances/accounts': typeof AppFinancesAccountsRoute
  '/finances/debts': typeof AppFinancesDebtsRoute
  '/finances/history': typeof AppFinancesHistoryRoute
  '/finances/income': typeof AppFinancesIncomeRoute
  '/finances/investments': typeof AppFinancesInvestmentsRoute
  '/finances/monthly': typeof AppFinancesMonthlyRoute
  '/finances/recurring': typeof AppFinancesRecurringRoute
  '/finances/savings': typeof AppFinancesSavingsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/trash': typeof AppNotesTrashRoute
  '/reading/library': typeof AppReadingLibraryRoute
  '/tasks/all': typeof AppTasksAllRoute
  '/tasks/backlog': typeof AppTasksBacklogRoute
  '/tasks/stats': typeof AppTasksStatsRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/tasks/weekly': typeof AppTasksWeeklyRoute
  '/finances': typeof AppFinancesIndexRoute
  '/notes': typeof AppNotesIndexRoute
  '/reading': typeof AppReadingIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pomodoro': typeof AppPomodoroRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/finances/accounts': typeof AppFinancesAccountsRoute
  '/_app/finances/debts': typeof AppFinancesDebtsRoute
  '/_app/finances/history': typeof AppFinancesHistoryRoute
  '/_app/finances/income': typeof AppFinancesIncomeRoute
  '/_app/finances/investments': typeof AppFinancesInvestmentsRoute
  '/_app/finances/monthly': typeof AppFinancesMonthlyRoute
  '/_app/finances/recurring': typeof AppFinancesRecurringRoute
  '/_app/finances/savings': typeof AppFinancesSavingsRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/notes/trash': typeof AppNotesTrashRoute
  '/_app/reading/library': typeof AppReadingLibraryRoute
  '/_app/tasks/all': typeof AppTasksAllRoute
  '/_app/tasks/backlog': typeof AppTasksBacklogRoute
  '/_app/tasks/stats': typeof AppTasksStatsRoute
  '/_app/tasks/today': typeof AppTasksTodayRoute
  '/_app/tasks/weekly': typeof AppTasksWeeklyRoute
  '/_app/finances/': typeof AppFinancesIndexRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/reading/': typeof AppReadingIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/onboarding'
    | '/pomodoro'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/finances/accounts'
    | '/finances/debts'
    | '/finances/history'
    | '/finances/income'
    | '/finances/investments'
    | '/finances/monthly'
    | '/finances/recurring'
    | '/finances/savings'
    | '/notes/$noteId'
    | '/notes/trash'
    | '/reading/library'
    | '/tasks/all'
    | '/tasks/backlog'
    | '/tasks/stats'
    | '/tasks/today'
    | '/tasks/weekly'
    | '/finances/'
    | '/notes/'
    | '/reading/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/onboarding'
    | '/pomodoro'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/finances/accounts'
    | '/finances/debts'
    | '/finances/history'
    | '/finances/income'
    | '/finances/investments'
    | '/finances/monthly'
    | '/finances/recurring'
    | '/finances/savings'
    | '/notes/$noteId'
    | '/notes/trash'
    | '/reading/library'
    | '/tasks/all'
    | '/tasks/backlog'
    | '/tasks/stats'
    | '/tasks/today'
    | '/tasks/weekly'
    | '/finances'
    | '/notes'
    | '/reading'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/$'
    | '/_app/ai'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/habits'
    | '/_app/onboarding'
    | '/_app/pomodoro'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/finances/accounts'
    | '/_app/finances/debts'
    | '/_app/finances/history'
    | '/_app/finances/income'
    | '/_app/finances/investments'
    | '/_app/finances/monthly'
    | '/_app/finances/recurring'
    | '/_app/finances/savings'
    | '/_app/notes/$noteId'
    | '/_app/notes/trash'
    | '/_app/reading/library'
    | '/_app/tasks/all'
    | '/_app/tasks/backlog'
    | '/_app/tasks/stats'
    | '/_app/tasks/today'
    | '/_app/tasks/weekly'
    | '/_app/finances/'
    | '/_app/notes/'
    | '/_app/reading/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pomodoro': {
      id: '/_app/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading/': {
      id: '/_app/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof AppReadingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/': {
      id: '/_app/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AppFinancesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/weekly': {
      id: '/_app/tasks/weekly'
      path: '/tasks/weekly'
      fullPath: '/tasks/weekly'
      preLoaderRoute: typeof AppTasksWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/today': {
      id: '/_app/tasks/today'
      path: '/tasks/today'
      fullPath: '/tasks/today'
      preLoaderRoute: typeof AppTasksTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/stats': {
      id: '/_app/tasks/stats'
      path: '/tasks/stats'
      fullPath: '/tasks/stats'
      preLoaderRoute: typeof AppTasksStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/backlog': {
      id: '/_app/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof AppTasksBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/all': {
      id: '/_app/tasks/all'
      path: '/tasks/all'
      fullPath: '/tasks/all'
      preLoaderRoute: typeof AppTasksAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading/library': {
      id: '/_app/reading/library'
      path: '/reading/library'
      fullPath: '/reading/library'
      preLoaderRoute: typeof AppReadingLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/trash': {
      id: '/_app/notes/trash'
      path: '/notes/trash'
      fullPath: '/notes/trash'
      preLoaderRoute: typeof AppNotesTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/savings': {
      id: '/_app/finances/savings'
      path: '/finances/savings'
      fullPath: '/finances/savings'
      preLoaderRoute: typeof AppFinancesSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/recurring': {
      id: '/_app/finances/recurring'
      path: '/finances/recurring'
      fullPath: '/finances/recurring'
      preLoaderRoute: typeof AppFinancesRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/monthly': {
      id: '/_app/finances/monthly'
      path: '/finances/monthly'
      fullPath: '/finances/monthly'
      preLoaderRoute: typeof AppFinancesMonthlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/investments': {
      id: '/_app/finances/investments'
      path: '/finances/investments'
      fullPath: '/finances/investments'
      preLoaderRoute: typeof AppFinancesInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/income': {
      id: '/_app/finances/income'
      path: '/finances/income'
      fullPath: '/finances/income'
      preLoaderRoute: typeof AppFinancesIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/history': {
      id: '/_app/finances/history'
      path: '/finances/history'
      fullPath: '/finances/history'
      preLoaderRoute: typeof AppFinancesHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/debts': {
      id: '/_app/finances/debts'
      path: '/finances/debts'
      fullPath: '/finances/debts'
      preLoaderRoute: typeof AppFinancesDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances/accounts': {
      id: '/_app/finances/accounts'
      path: '/finances/accounts'
      fullPath: '/finances/accounts'
      preLoaderRoute: typeof AppFinancesAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAiRoute: typeof AppAiRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppFinancesAccountsRoute: typeof AppFinancesAccountsRoute
  AppFinancesDebtsRoute: typeof AppFinancesDebtsRoute
  AppFinancesHistoryRoute: typeof AppFinancesHistoryRoute
  AppFinancesIncomeRoute: typeof AppFinancesIncomeRoute
  AppFinancesInvestmentsRoute: typeof AppFinancesInvestmentsRoute
  AppFinancesMonthlyRoute: typeof AppFinancesMonthlyRoute
  AppFinancesRecurringRoute: typeof AppFinancesRecurringRoute
  AppFinancesSavingsRoute: typeof AppFinancesSavingsRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesTrashRoute: typeof AppNotesTrashRoute
  AppReadingLibraryRoute: typeof AppReadingLibraryRoute
  AppTasksAllRoute: typeof AppTasksAllRoute
  AppTasksBacklogRoute: typeof AppTasksBacklogRoute
  AppTasksStatsRoute: typeof AppTasksStatsRoute
  AppTasksTodayRoute: typeof AppTasksTodayRoute
  AppTasksWeeklyRoute: typeof AppTasksWeeklyRoute
  AppFinancesIndexRoute: typeof AppFinancesIndexRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppReadingIndexRoute: typeof AppReadingIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAiRoute: AppAiRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppFinancesAccountsRoute: AppFinancesAccountsRoute,
  AppFinancesDebtsRoute: AppFinancesDebtsRoute,
  AppFinancesHistoryRoute: AppFinancesHistoryRoute,
  AppFinancesIncomeRoute: AppFinancesIncomeRoute,
  AppFinancesInvestmentsRoute: AppFinancesInvestmentsRoute,
  AppFinancesMonthlyRoute: AppFinancesMonthlyRoute,
  AppFinancesRecurringRoute: AppFinancesRecurringRoute,
  AppFinancesSavingsRoute: AppFinancesSavingsRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesTrashRoute: AppNotesTrashRoute,
  AppReadingLibraryRoute: AppReadingLibraryRoute,
  AppTasksAllRoute: AppTasksAllRoute,
  AppTasksBacklogRoute: AppTasksBacklogRoute,
  AppTasksStatsRoute: AppTasksStatsRoute,
  AppTasksTodayRoute: AppTasksTodayRoute,
  AppTasksWeeklyRoute: AppTasksWeeklyRoute,
  AppFinancesIndexRoute: AppFinancesIndexRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppReadingIndexRoute: AppReadingIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
